services:
  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-inovSmart-db
    profiles: [ "default", "all"]
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - inovSmart-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aliyara29" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak-inovSmart
    profiles: [ "default", "all", ]
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-inovSmart-db:5432/keycloak_db
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_PORT: 8080
    ports:
      - "8090:8080"
#    volumes:
#      - ./api-gateway/themes:/opt/keycloak/themes
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - inovSmart-network
networks:
  inovSmart-network:
    driver: bridge
volumes:
  keycloak-data: